FROM openjdk:8-jdk-alpine as builder

RUN apk update && apk add bash
RUN apk add --no-cache ca-certificates git

WORKDIR /usr/src/reportportal

COPY gradle/ ./gradle
COPY gradlew .
RUN ./gradlew wrapper

COPY build-quality.gradle build.gradle gradlew settings.gradle gradle.properties ./
RUN ./gradlew resolveDependencies

COPY . .
RUN ./gradlew build

FROM openjdk:8-jre-slim

ENV JAVA_OPTS="-Xmx512m -Djava.security.egd=file:/dev/./urandom"
ENV JAVA_APP=/service-authorization.jar

RUN echo '#!/bin/sh \n\
exec java $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh

VOLUME /tmp

COPY --from=builder /usr/src/reportportal/build/libs/$JAVA_APP .
COPY --from=builder /usr/src/reportportal/build/libs/lib /lib

RUN sh -c 'touch $JAVA_APP'

EXPOSE 8080

ENTRYPOINT ["/start.sh"]
